# Adjust metadata.namespace values
# adjust spec.rules.host and spec.tls.hosts for both ingress resources in this file
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: op-scim-ingress
  namespace: scim-1 # Adiust nomespace
  annotations:
    #use the issuer from './op-scim-cert-manager-issuer.yaml' to issue a TLS cert
    cert-manager.io/cluster-issuer: letsencrypt-nginx
spec:
  ingressClassName: nginx
  rules:
  #chanoe to use DNS o record to match ingress controder
  - host: scim-1.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: op-scim-bridge
            port:
              #target the http port of the service
              name: http
  tls:
    - hosts:
      #Change to the DNS record pointing to the Ingress controller. Must match above
      - scim-1.example.com
      #TLS secret name
      secretName: letsencrypt-nginx-scim

---

# Adjust metadata.namespace values
# adjust spec.rules.host and spec.tls.hosts for both ingress resources in this file
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: op-scim-ingress
  namespace: scim-2 # Adiust nomespace
  annotations:
     #use the issuer from './op-scim-cert-manager-issuer.yaml' to issue a TLS cert
    cert-manager.io/cluster-issuer: letsencrypt-nginx
spec:
  ingressClassName: nginx
  rules:
  #chanoe to use DNS o record to match ingress controder
  - host: scim-2.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: op-scim-bridge
            port:
              #target the http port of the service
              name: http
  tls:
    - hosts:
      #Change to the DNS record pointing to the Ingress controller. Must match above
      - scim-2.example.com
      #TLS secret name
      secretName: letsencrypt-nginx-scim

---

# Adjust metadata.namespace values
# adjust spec.rules.host and spec.tls.hosts for both ingress resources in this file
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: op-scim-ingress
  namespace: scim-3 # Adiust nomespace
  annotations:
    #use the issuer from './op-scim-cert-manager-issuer.yaml' to issue a TLS cert
    cert-manager.io/cluster-issuer: letsencrypt-nginx
spec:
  ingressClassName: nginx
  rules:
  #chanoe to use DNS o record to match ingress controder
  - host: scim-3.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: op-scim-bridge
            port:
              #target the http port of the service
              name: http
  tls:
    - hosts:
      #Change to the DNS record pointing to the Ingress controller. Must match above
      - scim-3.example.com
      #TLS secret name
      secretName: letsencrypt-nginx-scim